### ISSUE TITLE
Error with migration-test & LOAD_PROD_DATA results in 'empty' datadump

### ISSUE THREAD

**Issue by easherma** [cityofaustin/techstack#3159]
---
name: Bug report
about: Create a report to help us improve

---

**Describe the bug**
See title 

**To Reproduce**

Run LOAD_PROD_DATA=on ./scripts/migrations_test.sh
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/serializers/json.py", line 68, in Deserializer
    objects = json.loads(stream_or_string)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./joplin/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/modeltranslation/management/commands/loaddata.py", line 61, in handle
    return super(Command, self).handle(*fixture_labels, **options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 72, in handle
    self.loaddata(fixture_labels)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 114, in loaddata
    self.load_label(fixture_label)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 172, in load_label
    for obj in objects:
  File "/usr/local/lib/python3.6/site-packages/django/core/serializers/json.py", line 73, in Deserializer
    raise DeserializationError() from exc
django.core.serializers.base.DeserializationError: Problem installing fixture '/app/./joplin/db/system-generated/tmp_production.datadump.json': 
1
```

**Comment by easherma** [comment]
1) The bash script doesn't stop on this error, despite it being pretty significant. Is this a limitation of the bash script or can we add some error handling? 
2) I was able to manually do a dump from prod and ran: 
```
  heroku run -xa joplin python ./joplin/manage.py dumpdata --indent 2 --natural-foreign --natural-primary -- | \
    python ./scripts/remove_logs_from_json_stream.py | \
    jq '(.[] | select(.model == "users.user") | .fields.password) |= "pbkdf2_sha256$150000$GJQ1UoZlgrC4$Ir0Uww/i9f2VKzHznU4B1uaHbdCxRnZ69w12cIvxWP0="' \
    > seeding.datadump.json
```

However, when loading this data I got:
```
app_1     | django.db.utils.IntegrityError: Problem installing fixture '/app/./joplin/db/system-generated/seeding.datadump.json': Could not load wagtailcore.GroupCollectionPermission(pk=1): duplicate key value violates unique constraint "wagtailcore_groupcollect_group_id_collection_id_p_a21cefe9_uniq"
app_1     | DETAIL:  Key (group_id, collection_id, permission_id)=(1, 1, 4) already exists.
```

**Comment by Niicck** [comment]
Needed `--exclude=wagtailcore.GroupCollectionPermission`

**Comment by desigonz** [comment]
Can y'all size this issue?

**Comment by desigonz** [comment]
CLosing, will reopen if it happens again

**Comment by easherma** [comment]
This is happening for me again.
