### ISSUE TITLE
"There was a problem building Janis"

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#3477]
PRODUCTION -- Fri Nov 22 23:33:09 UTC 2019 e2e58f -- :x: There was a problem building janis. Check the logs for details. https://s3.amazonaws.com/janis-austin-gov-production/_reserved/logs/e2e58f13abe3cf321c49b73ed8fcdd771f58d16568a638f12fe4bed2cc328fa3.txt

**Comment by Jo-Dwyer** [comment]
@Niicck should I log failed builds whenever they happen?

**Comment by Niicck** [comment]
From https://app.netlify.com/sites/janis-3297-location/deploys/5ddbfcdb62c2eb0008d145c5
```
10:11:16 AM: 236/248 95% 16/s 0.7s
10:13:23 AM:   Error: Trace: { FetchError: request to https://joplin-staging.herokuapp.com/ap  i/graphql failed, reason: connect ETIMEDOUT 52.86.253.3:443
10:13:23 AM:       at ClientRequest.<anonymous> (/opt/build/repo/node_modules/node-fetch/lib/  index.js:1393:11)
10:13:23 AM:       at ClientRequest.emit (events.js:198:13)
10:13:23 AM:       at TLSSocket.socketErrorListener (_http_client.js:392:9)
10:13:23 AM:       at TLSSocket.emit (events.js:198:13)
10:13:23 AM:       at emitErrorNT (internal/streams/destroy.js:91:8)
10:13:23 AM:       at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
10:13:23 AM:       at process._tickCallback (internal/process/next_tick.js:63:19)
10:13:23 AM:     message:
10:13:23 AM:      'request to https://joplin-staging.herokuapp.com/api/graphql failed, reason  : connect ETIMEDOUT 52.86.253.3:443',
10:13:23 AM:     type: 'system',
10:13:23 AM:     errno: 'ETIMEDOUT',
10:13:23 AM:     code: 'ETIMEDOUT' }
10:13:23 AM:       at init.catch.e (/opt/build/repo/node_modules/react-static/bin/react-stati  c:6:11)
10:13:23 AM:       at process._tickCallback (internal/process/next_tick.js:68:7)
10:13:23 AM: 
10:13:23 AM: error Command failed with exit code 1.
```
