### ISSUE TITLE
Map Block in service steps throws errors

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#3567]
## Describe the bug
When you have a map_block in a service step, it throws unhandled errors in Joplin. Side effects unknown, but this would be good to clean up.

## To Reproduce
Steps to reproduce the behavior 
example: 
1. Save a draft or query a service page that has a map_block
2. See errors getting thrown on your server

## Current behavior
This error:
```
11 Dec 2019 13:43:26.203128 <190>1 2019-12-11T19:43:23.581664+00:00 app web.1 - - Traceback (most recent call last):
  File "/app/joplin/api/schema.py", line 93, in try_get_api_representation
    block = StreamChild.block.get_api_representation(StreamChild.value)
AttributeError: 'dict' object has no attribute 'block'Exception
11 Dec 2019 13:43:26.203128 <190>1 2019-12-11T19:43:23.581681+00:00 app web.1 - - Traceback (most recent call last):
  File "/app/joplin/api/schema.py", line 99, in try_get_api_representation
    parsed_block = {key: expand_by_type(key, value) for (key, value) in block.items()}
  File "/app/joplin/api/schema.py", line 99, in <dictcomp>
    parsed_block = {key: expand_by_type(key, value) for (key, value) in block.items()}
  File "/app/joplin/api/schema.py", line 88, in expand_by_type
    try_get_api_representation(value)
  File "/app/joplin/api/schema.py", line 105, in try_get_api_representation
    return block
UnboundLocalError: local variable 'block' referenced before assignment
11 Dec 2019 13:43:26.203128 <190>1 2019-12-11T19:43:23.581664+00:00 app web.1 - - Traceback (most recent call last):
  File "/app/joplin/api/schema.py", line 93, in try_get_api_representation
    block = StreamChild.block.get_api_representation(StreamChild.value)
AttributeError: 'dict' object has no attribute 'block'Exception
11 Dec 2019 13:43:26.203128 <190>1 2019-12-11T19:43:23.581681+00:00 app web.1 - - Traceback (most recent call last):
  File "/app/joplin/api/schema.py", line 99, in try_get_api_representation
    parsed_block = {key: expand_by_type(key, value) for (key, value) in block.items()}
  File "/app/joplin/api/schema.py", line 99, in <dictcomp>
    parsed_block = {key: expand_by_type(key, value) for (key, value) in block.items()}
  File "/app/joplin/api/schema.py", line 88, in expand_by_type
    try_get_api_representation(value)
  File "/app/joplin/api/schema.py", line 105, in try_get_api_representation
    return block
UnboundLocalError: local variable 'block' referenced before assignment11 Dec 2019 13:43:26.203128 <190>1 2019-12-11T19:43:23.581664+00:00 app web.1 - - Traceback (most recent call last):
  File "/app/joplin/api/schema.py", line 93, in try_get_api_representation
    block = StreamChild.block.get_api_representation(StreamChild.value)
AttributeError: 'dict' object has no attribute 'block'Exception
11 Dec 2019 13:43:26.203128 <190>1 2019-12-11T19:43:23.581681+00:00 app web.1 - - Traceback (most recent call last):
  File "/app/joplin/api/schema.py", line 99, in try_get_api_representation
    parsed_block = {key: expand_by_type(key, value) for (key, value) in block.items()}
  File "/app/joplin/api/schema.py", line 99, in <dictcomp>
    parsed_block = {key: expand_by_type(key, value) for (key, value) in block.items()}
  File "/app/joplin/api/schema.py", line 88, in expand_by_type
    try_get_api_representation(value)
  File "/app/joplin/api/schema.py", line 105, in try_get_api_representation
    return block
UnboundLocalError: local variable 'block' referenced before assignment11 Dec 2019 13:43:26.203128 <190>1 2019-12-11T19:43:23.581664+00:00 app web.1 - - Traceback (most recent call last):
  File "/app/joplin/api/schema.py", line 93, in try_get_api_representation
    block = StreamChild.block.get_api_representation(StreamChild.value)
AttributeError: 'dict' object has no attribute 'block'Exception
11 Dec 2019 13:43:26.203128 <190>1 2019-12-11T19:43:23.581681+00:00 app web.1 - - Traceback (most recent call last):
  File "/app/joplin/api/schema.py", line 99, in try_get_api_representation
    parsed_block = {key: expand_by_type(key, value) for (key, value) in block.items()}
  File "/app/joplin/api/schema.py", line 99, in <dictcomp>
    parsed_block = {key: expand_by_type(key, value) for (key, value) in block.items()}
  File "/app/joplin/api/schema.py", line 88, in expand_by_type
    try_get_api_representation(value)
  File "/app/joplin/api/schema.py", line 105, in try_get_api_representation
    return block
UnboundLocalError: local variable 'block' referenced before assignment
```

## Expected behavior
No errors.

**Comment by easherma** [comment]
https://github.com/cityofaustin/joplin/pull/554 fixed this
